//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletaCurso
    {
        public int Id_BoletaCurso { get; set; }
        public int FKId_Curso_BoletaCurso { get; set; }
        public int FKId_Empleado_BoletaCurso { get; set; }
        public decimal CantidadHoras_BoletaCurso { get; set; }
        public decimal MontoPagar_BoletaCurso { get; set; }
        public int CantidadEstudiantes_BoletaCurso { get; set; }
        public System.DateTime FechaCurso_BoletaCurso { get; set; }
        public int FKId_PeriodoDePago_BoletaCurso { get; set; }
        public bool PagoProcesado_BoletaCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
