//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoAplicado
    {
        public int Id_ConceptoAplicado { get; set; }
        public decimal Cantidad_ConceptoAplicado { get; set; }
        public decimal Monto_ConceptoAplicado { get; set; }
        public int FKId_Concepto_ConceptoAplicado { get; set; }
    }
}
