//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concepto()
        {
            this.ConceptoAplicado = new HashSet<ConceptoAplicado>();
            this.PlanillaDetalle = new HashSet<PlanillaDetalle>();
            this.PlanillaPatronoDetalle = new HashSet<PlanillaPatronoDetalle>();
        }
    
        public int Id_Concepto { get; set; }
        public string Nombre_Concepto { get; set; }
        public bool Editable_Concepto { get; set; }
        public int FKId_TipoConcepto_Concepto { get; set; }
        public int FKId_DestinatarioConcepto_Concepto { get; set; }
        public int FKId_ImpactaPlanilla_Concepto { get; set; }
        public int FKId_ClaseConcepto_Concepto { get; set; }
        public Nullable<decimal> Porcentaje_Concepto { get; set; }
        public Nullable<decimal> MontoFijo_Concepto { get; set; }
        public bool DirectoPlanilla_Concepto { get; set; }
        public Nullable<decimal> FactorTiempo_Concepto { get; set; }
    
        public virtual ClaseConcepto ClaseConcepto { get; set; }
        public virtual DestinatarioConcepto DestinatarioConcepto { get; set; }
        public virtual ImpactaPlanilla ImpactaPlanilla { get; set; }
        public virtual TipoConcepto TipoConcepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConceptoAplicado> ConceptoAplicado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDetalle> PlanillaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaPatronoDetalle> PlanillaPatronoDetalle { get; set; }
    }
}
