//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deduccion()
        {
            this.PlanillaDeduccion = new HashSet<PlanillaDeduccion>();
        }
    
        public int Id_Deduccion { get; set; }
        public string Nombre_Deduccion { get; set; }
        public decimal Porcentaje_Deduccion { get; set; }
        public int FKId_TipoDeduccion_Deduccion { get; set; }
    
        public virtual TipoDeduccion TipoDeduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDeduccion> PlanillaDeduccion { get; set; }
    }
}
