//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id_Direccion { get; set; }
        public string Detalle_Direccion { get; set; }
        public int FKIdDistrito_Direccion { get; set; }
        public int FKIdCanton_Direccion { get; set; }
        public int FKIdProvincia_Direccion { get; set; }
        public int FKId_Persona_Direccion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
