//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incapacidad
    {
        public int Id_Incapacidad { get; set; }
        public decimal Dias_Incapacidad { get; set; }
        public bool Procesado_Incapacidad { get; set; }
        public int FKId_PeriodoDePago_Incapacidad { get; set; }
        public int FKId_TipoIncapacidad_Incapacidad { get; set; }
        public int FKId_Empleado_Incapacidad { get; set; }
        public System.DateTime FechaActualizacion_Incapacidad { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PeriodoDePago PeriodoDePago { get; set; }
        public virtual TipoIncapacidad TipoIncapacidad { get; set; }
    }
}
