//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public int Id_Liquidacion { get; set; }
        public System.DateTime FechaActualizacion_Liquidacion { get; set; }
        public decimal DiasVacaciones_Liquidacion { get; set; }
        public decimal MontoVacaciones_Liquidacion { get; set; }
        public decimal AniosLaborados_Liquidacion { get; set; }
        public decimal MontoCesantia_Liquidacion { get; set; }
        public decimal MontoPreaviso_Liquidacion { get; set; }
        public decimal MontoAguinaldo_Liquidacion { get; set; }
        public int FKId_Preaviso_Liquidacion { get; set; }
        public int FKId_Empleado_Liquidacion { get; set; }
        public bool LiquidacionPagada_Liquidacion { get; set; }
        public int FKId_TipoSalidaLiquidacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Preaviso Preaviso { get; set; }
        public virtual TipoSalida TipoSalida { get; set; }
    }
}
