//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogSolicitud()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int Id_LogSolicitud { get; set; }
        public int FKId_EmpleadoModificador_LogSolicitud { get; set; }
        public System.DateTime FechaActualizacion_LogSolicitud { get; set; }
        public int FKId_StatusSolicitud_LogSolicitud { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual StatusSolicitud StatusSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
