//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planilla()
        {
            this.PlanillaDeduccion = new HashSet<PlanillaDeduccion>();
            this.PlanillaDetalle = new HashSet<PlanillaDetalle>();
        }
    
        public int Id_Planilla { get; set; }
        public System.DateTime FechaActualizacion_Planilla { get; set; }
        public int FKId_Empleado_Planilla { get; set; }
        public int FKId_PeriodoDePago_Planilla { get; set; }
        public decimal TotalDeducciones_Planilla { get; set; }
        public decimal TotalAsignaciones_Planilla { get; set; }
        public decimal TotalMontoaPagar_Planilla { get; set; }
        public bool PagoProcesado_Planilla { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PeriodoDePago PeriodoDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDeduccion> PlanillaDeduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDetalle> PlanillaDetalle { get; set; }
    }
}
