//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaDeduccion
    {
        public int FKId_Planilla_PlanillaDeduccion { get; set; }
        public int FKId_Deduccion_PlanillaDeduccion { get; set; }
        public System.DateTime FechaActualizacion_PlanillaDeducion { get; set; }
    
        public virtual Planilla Planilla { get; set; }
        public virtual Deduccion Deduccion { get; set; }
    }
}
