//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int Id_Solicitud { get; set; }
        public int FKId_TipoSolicitud_Solicitud { get; set; }
        public int FKId_EmpleadoSolicitante_Solicitud { get; set; }
        public string DetalleSolicitud_Solicitud { get; set; }
        public int Cantidad_dias_Solicitud { get; set; }
        public System.DateTime FechaInicioPeriodo_Solicitud { get; set; }
        public System.DateTime FechaFinPeriodo_Solicitud { get; set; }
        public int FKId_LogSolicitud_Solicitud { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual LogSolicitud LogSolicitud { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
    }
}
