//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int Id_Solicitud { get; set; }
        public int FKId_StatusSolicitud_Solicitud { get; set; }
        public int FKId_TipoSolicitud_Solicitud { get; set; }
        public System.DateTime FechaCreacion_Solicitud { get; set; }
        public Nullable<System.DateTime> FechaFin_Solicitud { get; set; }
        public int FKId_EmpleadoSolicitante_Solicitud { get; set; }
        public Nullable<int> FKId_EmpleadoAprobador_Solictud { get; set; }
        public string DetalleSolicitud_Solicitud { get; set; }
        public Nullable<int> Cantidad_dias_Solicitud { get; set; }
        public Nullable<System.DateTime> FechaInicioPeriodo_Solicitud { get; set; }
        public Nullable<System.DateTime> FechaFinPeriodo_Solicitud { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual StatusSolicitud StatusSolicitud { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
    }
}
