//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Planilla_CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int Id_Vacaciones { get; set; }
        public decimal AcumuladoDias_Vacaciones { get; set; }
        public int FKId_Empleado_Vacaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
